### ISSUE TITLE
PHP 7.4 introduced BC break with accessing null

### ISSUE THREAD

**Issue by glensc** [laminas/laminas-config#8]
This construct used to work, and pretty much the Zend Config is built around that accessing `NULL` as array yields no notices:

```
$ php --version
PHP 7.4.6 (cli) (built: May 29 2020 01:44:57) ( NTS )
$ php -r '$a=null; $a["bla"];'
PHP Notice:  Trying to access array offset on value of type null in Command line code on line 1
```

- https://www.php.net/manual/en/migration74.incompatible.php:
> ### Array-style access of non-arrays ¶
> Trying to use values of type null, bool, int, float or resource as an array (such as $null["key"]) will now generate a notice.

rfc:
- https://wiki.php.net/rfc/notice-for-non-valid-array-container

**Comment by glensc** [comment]
More particular, it's visible in such constructs:

```
$ PHP_VERSION=7.4 php -r 'require "vendor/autoload.php"; $c = new Zend\Config\Config([]); $c["blah"]["blah"];'
PHP Notice:  Trying to access array offset on value of type null in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0

Notice: Trying to access array offset on value of type null in Command line code on line 1

Call Stack:
    0.0004     401592   1. {main}() Command line code:0

$ PHP_VERSION=7.3 php -r 'require "vendor/autoload.php"; $c = new Zend\Config\Config([]); $c["blah"]["blah"];'

$
```

**Comment by weierophinney** [comment]
I've confirmed this with the following test within `test/ConfigTest.php`:

```php
    /**
     * @see https://github.com/laminas/laminas-config/issues/8
     */
    public function testNoNoticesEmittedWhenAccessingNonExistentNestedValueOfNonExistentParent()
    {
        if (PHP_VERSION_ID < 70400) {
            $this->markTestSkipped('Only relevant starting with PHP 7.4.0');
        }

        $config = new Config([]);
        $this->assertNull($config['not']['set']);
    }
```

The problem is... we have no idea when somebody is trying to unfurl a nested value. `Config::get()` (to which `Config::__get()` and, ultimately, `Config::offsetGet()`, proxies) checks to see if the element requested exists, and, if so, returns it, but otherwise returns a default value (generally `null`). It has no idea if there is a further lookup on a nested value.

So, `$c['blah']` returns `null`, and then PHP evaluates `null['blah']`. In previous versions, this worked without emitting a notice, but with 7.4, it now does.

Unfortunately, I have no idea for a workaround. Even calling `$config->toArray()['blah']['blah']` will result in notices (two, actually: `Undefined index` and `Trying to access array offset on value of type null`).

What you **CAN** do is use null coalesce to resolve this:

```php
$value = $config['blah']['blah'] ?? null;
```

which emits no notices, and accomplishes the same thing.

**Comment by Xerkus** [comment]
Sorry, but what is the issue here? This behavior is consistent with a regular array behavior.

**Comment by glensc** [comment]
As nothing can be done, as PHP language changed behavior, I guess the only thing left to do is document this and offer a solution in that documentation.

**Comment by glensc** [comment]
Good news is that this has issue only on nested accesses, i.e having missing value for top-level key and accessing it goes on without any warning and returns null.

```
➔ php -r 'require "vendor/autoload.php"; $config = new \Zend\Config\Config(["nested" => []]); var_dump($config["blah"], $config["nested"]["blah"]);'
Command line code:1:
NULL
Command line code:1:
NULL
```

so, solution for applications is to initialize top-level arrays with empty arrays. still better than doing massive null-coalesce changes in the codebase.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
